#!/usr/bin/env bash

output=$(playerctl metadata --format "{{ title }} - {{ artist }}")
status=$(playerctl status)
title=$(playerctl metadata title)
artist=$(playerctl metadata artist)
artUrl=$(playerctl metadata mpris:artUrl)

if [[ "$status" == "Playing" || "$status" == "Paused" ]]; then
  position=$(playerctl position 2>/dev/null)
  duration=$(playerctl metadata mpris:length 2>/dev/null)
  # progress=$(( (${position%.*} * 100) / (${duration} / 1000000) ))
  echo "{
    \"state\": \"on\", 
    \"isPlaying\": \"${status}\", 
    \"title\": \"${title}\", 
    \"artist\": \"${artist}\", 
    \"artUrl\": \"${artUrl}\", 
    \"position\": ${position},
    \"duration\": ${duration}
  }"
else
  echo "{\"state\": \"off\"}"
fi
