#!/usr/bin/env bash

output=$(playerctl metadata --format "{{ title }} - {{ artist }}")
status=$(playerctl status)

if [[ "$status" == "Playing" || "$status" == "Paused" ]]; then
  eww update visibility_media=true
  echo $(playerctl metadata --format "{{ title }} - {{ artist }}")
else
  eww update visibility_media=false
fi
