#!/usr/bin/env bash

LATITUDE=53.0752
LONGITUDE=8.8078
UNITS="metric"
EXCLUDE="minutely,hourly,alerts"
OPENWEATHERMAP_API_KEY=`cat ~/.config/eww/.weather_api.env`
response=$(curl -s "https://api.openweathermap.org/data/3.0/onecall?lat=${LATITUDE}&lon=${LONGITUDE}&units=${UNITS}&exclude=${EXCLUDE}&appid=${OPENWEATHERMAP_API_KEY}")

declare -A icons
icons=(
  ["Clear"]=""
  ["Clouds"]=""
  ["Rain"]=""
  ["Drizzle"]=""
  ["Thunderstorm"]=""
  ["Snow"]=""
  ["Mist"]=""
  ["Fog"]=""
  ["Haze"]=""
  ["Smoke"]=""
  ["Dust"]=""
  ["Sand"]=""
  ["Ash"]=""
  ["Squall"]=""
  ["Tornado"]=""
)

if [ $? -eq 0 ] && [ ! -z "$response" ]; then
    # Current weather
    current_temp=$(printf "%.0f" $(echo "$response" | jq '.current.temp'))
    current_weather=$(echo "$response" | jq -r '.current.weather[0].main')
    current_icon=${icons[$current_weather]}

    # 3 day forecast
    forecast=""
    for i in {1..3}; do
        temp=$(printf "%.0f" $(echo "$response" | jq ".daily[$i].temp.day"))
        weather=$(echo "$response" | jq -r ".daily[$i].weather[0].main")
        icon=${icons[$weather]}
        if [ $i -eq 3 ]; then
            forecast="${forecast}${icon} ${temp}°"
        else
            forecast="${forecast}${icon} ${temp}° "
        fi
    done
    
    # Output for EWW bar
    echo "${current_icon} ${current_temp}° ${current_weather} | ${forecast}"
else
    echo "Error: Weather data unavailable"
    exit 1
fi