#!/usr/bin/env bash

OUT="$(xdg-user-dir VIDEOS)/recordings/$(date +%Y-%m-%d_%H-%M%S).mp4"

trap 'notify-send "Recording" "Recording interrupted\nSaved to: $OUT" -i camera-video; exit' SIGINT SIGTERM

if pgrep -x "wl-screenrec" > /dev/null; then
  killall wl-screenrec
  eww update screen_record=false
else
  # Start new recording
  OUT="$(xdg-user-dir VIDEOS)/recordings/$(date +%Y-%m-%d_%H-%M%S).mp4"
  dunstify "Recording" "Screen recording started" -i camera-video
  eww update screen_record=true

  #wl-screenrec --low-power=off --audio --audio-device alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink.monitor -f "$OUT" &
  wl-screenrec --low-power=off --audio -f "$OUT" &

  PID=$!

  wait $PID
  ACTION=$(dunstify "Recording Finished" "Saved to: $OUT" -i camera-video --action="open,Open Video")

  case "$ACTION" in
  "open")
      xdg-open $OUT
      ;;
  "2")
      ;;
  esac
fi
