# Aliases
alias ls='exa --color=auto'
alias cat='bat'
alias grep='rg'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias dotfilestui='/usr/bin/gitui -d=$HOME/.dotfiles/ -w=$HOME'
alias ssh='kitten ssh'
alias packages='expac -H M '%m\t%n' | sort -h'
alias nextcloud='sudo systemctl start home-thejayduck-Nextcloud.mount'
alias convert2webm='ffmpeg -i $1 -c:v libvpx-vp9 -crf 35 $2'
