#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null & 
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v dunst)" ]; then
  dunst &
fi

$HOME/.fehbg &
greenclip daemon &
xscreensaver --no-splash &
flameshot &

index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do 
  barname="mainbar$index"
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar/config.ini &> /dev/null &
  let index=index+1
done

